### ISSUE TITLE
Missing installation guidance.

### ISSUE THREAD

**Issue by Antonio-Iliev** [Mini-IT/AdvertisingIdentifierFetcher#1]
Please add a section for installation in the documentation, including mentioning using the package Google External Dependency Manager or similar for resolving the android dependencies. Or even better include it as a dependency in package.json file.

**Comment by gluks** [comment]
Thanks for interesting the project.
I've added a short intallation guide. I beleive it's quite simple and there is no need to write more detailed instuctions.
May be I missed something.

**Comment by Antonio-Iliev** [comment]
Great! Thank you for the update.
