### ISSUE TITLE
Add isLimitAdTracking and error to output

### ISSUE THREAD

**Issue by pspgit** [Mini-IT/AdvertisingIdentifierFetcher#2]
I'd suggest adding isLimitAdTracking and error message to output of GetAdvertisingIdAsync().

`bool isLimitAdTracking = adIdInfo.Call<bool>("isLimitAdTrackingEnabled");`

This would make method interface match Unity's Application.RequestAdvertisingIdentifierAsync() and allow caller to decide how to process error message, etc.

**Comment by gluks** [comment]
Yes. This makes sense. I think I'll do it later.
Tanks for the suggestion.

**Comment by gluks** [comment]
1.3.0 released
